### ISSUE TITLE
Scanning is relative to the player even when in cursor mode, version 0.1.1

### ISSUE THREAD

**Issue by MyNameIsTrez** [Crimso777/Factorio-Access#21]
I think it is annoying how scanning is useless when in cursor mode due to the scanning always being relative to the player. When I'm building in cursor mode I'd like to be able to stay in cursor mode for as long as possible, but this isn't always possible when I need to scan for something I want to build next to. As a counterexample, pressing the K key when in cursor mode does already correctly read the coordinates of the cursor instead of the coordinates of the player, which is very useful.

**Comment by Crimso777** [comment]
Fixed and pushed.
