### ISSUE TITLE
The right bracket key has inconsistent behavior, version 0.1.1

### ISSUE THREAD

**Issue by MyNameIsTrez** [Crimso777/Factorio-Access#22]
If you open the inventory of a furnace and right-click coal into the fuel slot, it drops a single coal item from your hand into the fuel slot. On the other hand, the vanilla behavior of Factorio for the right bracket key is putting half of what you have in your hand into the fuel slot. This vanilla behavior is already part of the mod, since when you use the Control plus Right Bracket key on a selected furnace it will put half of what you have in your hand in there. Vanilla Factorio uses the Z key to drop a single item, but because that's so far away from the left and right bracket keys it may be best to have it be a key near the left and right bracket. Maybe the backslash key, or P, or semicolon, etc?

**Comment by EphDoering** [comment]
I just tested this and I think the current behavior matches vanilla right
click.
Right click will drop one item into the inventory slot that you click on.
Z will also drop one item into a machine, but I think it's primarily used
to drop items onto the ground or belt. Which should work as is right now.

**Comment by MyNameIsTrez** [comment]
Never mind me, I didn't realize that right-clicking into a slot would only dump a single item while it was right-clicking that takes out half of a slot.
